### PR TITLE
FEATURE - Update spacelift module example with name and terraform provider

### PR DESCRIPTION
**Pull request by spitzzz**
## Description of the change

Updating example for `spacelift_module` resource type to include the use of `name` and `terraform_provider`. When these arguments are not specified, Spacelift will inherently look in the Git repository name for this information. This is a bit confusing, so preferably having this information in our example will make things more clear.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation (non-breaking change that adds documentation)

## Related issues

N/A

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review

- [X] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [X] Pull Request is no longer marked as "draft"
- [ ] Reviewers have been assigned
- [ ] Changes have been reviewed by at least one other engineer
- [X] The target branch is `future` unless the change is going directly into production

### CODE REVIEW

**Review by marcinwyszynski — COMMENTED** [review]
Can we have 2 examples though? One Hashi-style with conventional repo name, and one Spacelift-style with custom name + provider + maybe custom project root?

**Comment by cube2222** [comment]
Please rebase onto the future branch.

**Comment by spitzzz** [comment]
> Can we have 2 examples though? One Hashi-style with conventional repo name, and one Spacelift-style with custom name + provider + maybe custom project root?

Great idea, I just added an additional example. In this case the additional example is "conventional style." I've added a note informing users that when the `name` and `provider` are not specified, the Git repository must follow the `terraform-${PROVIDER}-${NAME}` naming scheme. The example also shows the use of a custom `project_root`.

> Please rebase onto the future branch.

I've pulled in the latest changes from `future` just now

**Comment by spitzzz** [comment]
Closing for https://github.com/spacelift-io/terraform-provider-spacelift/pull/266

**Pull request closed without merging**
