### PR TITLE
Add resource for bitbucket datacenter integration handling

### PR DESCRIPTION
**Pull request by mplushnikov**
## Description of the change

Add resource for bitbucket datacenter integration handling, added username to data bitbucket_datacenter_integration

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (non-breaking change that adds documentation)

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development
- [x] Examples for new resources and data sources have been added
- [ ] Default values have been documented in the description (e.g., "Dummy: (Boolean) Blah blah. Defaults to `false`.)
- [x] If the action fails that checks the documentation: Run `go generate` to make sure the docs are up to date

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] Pull Request is no longer marked as "draft"
- [ ] Reviewers have been assigned
- [ ] Changes have been reviewed by at least one other engineer

### CODE REVIEW

**Comment by marcinwyszynski** [comment]
Adding @jmfontaine as the final decision maker.

**Comment by peterdeme** [comment]
@mplushnikov thank you for the contribution, we'll merge it 🙏 

one thing though is that the GitHub Action job contains secrets, and GitHub won't allow running that job when the source branch is a fork. I'll open a separate PR where I copy your code and merge that, if that's okay for you.

**Review by truszkowski — APPROVED** [review]

**Comment by mplushnikov** [comment]
@peterdeme Sure, feel free to do anything you need!

**Comment by peterdeme** [comment]
Continuation in https://github.com/spacelift-io/terraform-provider-spacelift/pull/498
Thanks again @mplushnikov

**Comment by peterdeme** [comment]
hey @mplushnikov, a little update from our side. so my other pull request that I opened for this one fails currently.

this is because we can only have 1 Bitbucket DC at a time, so the unit test cannot create another one.
believe it or not, this is exactly the feature that we're working on now: to be able to have multiple VCS integrations per account. it'll be released in February. when that comes, we'll slightly refactor the PR and the test will succeed.

Sorry for the inconvenience, we'll merge that PR as soon as the feature is released. 🙏 🙏

**Pull request closed without merging**
