### PR TITLE
feat: Add support for description on policies

### PR DESCRIPTION
**Pull request by mohamed-haidara-cko**
## Description of the change

This PR adds support for setting the `description` of policies.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (non-breaking change that adds documentation)

## Related issues

N/A

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development
- [ ] Examples for new resources and data sources have been added
- [ ] Default values have been documented in the description (e.g., "Dummy: (Boolean) Blah blah. Defaults to `false`.)
- [ ] If the action fails that checks the documentation: Run `go generate` to make sure the docs are up to date

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] Pull Request is no longer marked as "draft"
- [ ] Reviewers have been assigned
- [ ] Changes have been reviewed by at least one other engineer

### CODE REVIEW

**Comment by mohamed-haidara-cko** [comment]
The doc check is failing. Seems like the attributes need to be sorted (?)

**Comment by michieldewilde** [comment]
@mohamed-haidara-cko did you generate the documentation by running:
```
cd tools
go generate ./...
```

There's no need to edit the generated markdown files yourself.

**Comment by mohamed-haidara-cko** [comment]
> @mohamed-haidara-cko did you generate the documentation by running:
> 
> ```
> cd tools
> go generate ./...
> ```
> 
> There's no need to edit the generated markdown files yourself.

Now yes :-) 

Was a little bit confused 🤦

**Comment by michieldewilde** [comment]
@mohamed-haidara-cko moved to #530. Our tests rely on GitHub secrets and don't work with forks.

**Comment by mohamed-haidara-cko** [comment]
My [last commit](https://github.com/spacelift-io/terraform-provider-spacelift/pull/529/commits/eafc36d1065bff9a6714cfb449418e4ca0cd262d) should fix the test. You can cherry-pick it :-)

**Comment by marcinwyszynski** [comment]
LOL @mohamed-haidara-cko thanks, I fixed it the same way in the other PR :)

**Comment by michieldewilde** [comment]
@mohamed-haidara-cko, would it be possible for you to sign your commits?

**Comment by mohamed-haidara-cko** [comment]
> @mohamed-haidara-cko, would it be possible for you to sign your commits? We can't merge until the commits are signed, and we would prefer to not sign your commits.

Done. Squashed my commits with my key

**Comment by mwasilew2** [comment]
@marcinwyszynski is conditionally setting the description in the other PR: https://github.com/spacelift-io/terraform-provider-spacelift/blob/b63f6c21390299f5ad97b7fbe615aeaf6ee309e8/spacelift/resource_policy.go#L199  and the fork is just setting it inline in the struct, the same way the other fields are set.

@marcinwyszynski do you think the other fields should be set conditionally as well?

@michieldewilde other than that the change looks good. I think we can merge this PR and if we decide to set all fields conditionally we can do that in a separate PR.

**Review by mwasilew2 — APPROVED** [review]

**Comment by michieldewilde** [comment]
Merged #530. Closing this PR.
@mohamed-haidara-cko, thank you for the contribution!

**Pull request closed without merging**
